spring.application.name=chatApp
db.url=jdbc:postgresql://localhost:5432/CHATAPP
db.username=postgres
db.password=11201_VivekBhalke
db.driver=org.postgresql.Driver

hibernate.hbm2ddl.auto=update
hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
hibernate.show-sql=true
hibernate.format_sql=true
 Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/CHATAPP
spring.datasource.username=postgres
spring.datasource.password=11201_VivekBhalke
spring.datasource.driver-class-name=org.postgresql.Driver
#
## Hibernate Configuration
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.properties.hibernate.hbm2ddl.auto=update
#spring.jpa.properties.hibernate.show_sql=true
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.properties.hibernate.current_session_context_class=org.springframework.orm.hibernate5.SpringSessionContext
